name: Build Laravel + Vue + Tailwind CSS

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  build-os:
    name: System
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Update OS
        run: sudo apt update && sudo apt upgrade -y
          
  php-install:
      needs: build-os
      runs-on: ubuntu-latest
    
      steps:
      - name: PHP Install
        run: sudo apt install --no-install-recommends php8.1 && sudo apt-get install -y php8.1-cli php8.1-common php8.1-mysql php8.1-zip php8.1-gd php8.1-mbstring php8.1-curl php8.1-xml php8.1-bcmath
