name: Build Laravel + Vue + Tailwind CSS

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  build-os:
    name: System
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Update OS
        run: apt update & apt upgrade -y
          
  test:
      needs: build-os
      runs-on: ubuntu-latest
    
      steps:
      - name: Set up Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Upgrade PIP
        run: python -m pip install --upgrade pip
